### ISSUE TITLE
a is considered a consonant

### ISSUE THREAD

**Issue by 1j01** [boo1ean/symbols#1]
See https://github.com/boo1ean/tensify/issues/1

https://github.com/boo1ean/symbols/blob/d57f1b409379bc6a2e84f9bbe4f081dba8d623ef/src/helpers.js#L6

'a' shouldn't be in there! 😄
it's also copied to the README and tests:
https://github.com/boo1ean/symbols/blob/d57f1b409379bc6a2e84f9bbe4f081dba8d623ef/test/helpers.js#L11

and btw, "vowel" is spelled wrong in the API and tests (and package.json),
and in the tests it calls both vowels and consonants "vovels"

**Comment by boo1ean** [comment]
Thanks for your observations.
